---
##==## ANSIBLE GALAXY ROLE DEPENDENCIES ##==##
roles:
  - name: devsec.hardening
    src: devsec.hardening
    version: 7.0.0

collections:
  - name: community.general
  - name: ansible.posix